using System;

namespace EdB.Interface
{
	public enum InventoryType
	{
		UNKNOWN,
		ITEM_RESOURCE,
		ITEM_FOOD,
		ITEM_OTHER,
		ITEM_APPAREL,
		ITEM_EQUIPMENT,
		ITEM_SCHEMATIC,
		BUILDING_OTHER,
		BUILDING_FURNITURE,
		BUILDING_SECURITY,
		BUILDING_STRUCTURE,
		BUILDING_POWER,
		BUILDING_SHIP,
		BUILDING_PRODUCTION,
		BUILDING_JOY,
		BUILDING_TEMPERATURE,
		BUILDING_FOOD_UTILITIES
	}
}
